= Test case for an issue with vim-repeat/vim-surround

== Repository contents

* A minimal `init.vim` that maps `dp` to a function which makes it repeatable,
  using the implementation provided in the
  https://www.vikasraj.dev/blog/vim-dot-repeat[Dot-Repeat in Vim and Neovim]
  blog post (which thankfully provides snippets in both Lua and Vim Script).
* The plugins `vim-repeat` and `vim-surround` as submodules, at their latest
  version (as of the creating of this repository). Checked out in `pack`.
* Two text files to be opened with `vi -d original.txt changed.txt`, to easily
  test the plugins and the mapping.

== Minimal setup to reproduce the problem

I have placed everything in the repository for easy testing with Vim or Neovim
in an isolated environment. I recommend that to make sure no other plugin or
custom setting is the culprit (because, for a while, I was triggering the
problem inconsistently, as other plugins can make use of `vim-repeat`, and I
suspected that another plugin might be the issue, so I think it is important to
make a minimal test case like this). I've narrowed it down to only the
configuration/plugins provided here.

The `NVIM_APPNAME` feature from Neovim is the most convenient:

. `export NVIM_APPNAME='nvimtest`.
. Clone the repository as `~/.config/nvimtest`.

Of course, `nvimtest` is just an example, use what you like.

For testing with Vim, move away your `~/.vim` directory and use this repository
in its place:

. `mv ~/.vim ~/.vim.saved`
. Clone the repository as `~/.vim`.

If you are in a hurry, perhaps you can copy the snippet in the `init.vim` from
this repository to your config, and reproduce the issue still. If you only have
a Lua init file, this should be equivalent if added to your `init.lua`:

[source,lua]
----
Init = {} -- Just a global to hold the function to be called from Vim Script

local function make_repeatable(from, function_name, function_body)
    Init[function_name] = function(motion)
        if motion == nil then
            vim.o.operatorfunc = 'v:lua.Init.' .. function_name
            return 'g@l'
        end
        function_body()
    end
    vim.keymap.set('n', from, Init[function_name], { expr = true })
end

make_repeatable('dp', 'diff_put', function()
    vim.cmd('normal! dp')
end)
----

I have been able to reproduce the issue on Vim 8.2, Vim 9.1 Neovim 0.9 and
0.10.


== Instructions to reproduce the issue after setup

. `vi -d original.txt changed.txt`.
. Try the following to *not* trigger the issue, but confirm that `dp` is
  repeatable:
.. `]c` to go to the first change.
.. `dp` to put the first change.
.. Now, dot-repeat for the other two changes: `]c.]c.` (the `.` repeats `dp` as
   desired).
. Try the following to *do reproduce* the issue, by using `vim-surround`, which
  activates `vim-repeat` and remaps `.`:
.. `]c` to go to the first change.
.. Use `cs"'` to change the quotes of the first change.
.. `dp` to put the first change.
.. Now, move to the second change, and repeat: `]c.`. This repeats `cs"'` not
   `dp`.
.. Do `dp` again. It works, but it's still not repeatable. `]c.` still does
   `cs"'`, not `dp`.

== Workarounds

* Unmap `.`. Works, but then `vim-surround` or other plugins that use
  `vim-repeat` won't be repeatable.
* Uninstall `vim-repeat`. Same.
* Implement the `dp` mapping by using `vim-repeat`, like this: `nnoremap
  <silent> dp dp:silent! call repeat#set('dp', v:count)<Enter>`. This works for
  one's own maping, but rewriting the mapping from third party plugins or making
  them "opt-in" into `vim-repeat` if available might not be an option.
